const KEY='jeeAscensionV5';
const UNIT_DEADLINES=[['Maths','Algebra','2026-10-16'],['Maths','Trigonometry','2026-10-23'],['Maths','Coordinate Geometry','2026-11-05'],['Maths','Calculus','2026-12-01'],['Maths','Vectors & 3D','2026-12-10'],['Physics','Mechanics I','2026-10-10'],['Physics','Mechanics II','2026-10-22'],['Physics','Thermal Physics','2026-10-31'],['Physics','Waves & Oscillations','2026-11-12'],['Chemistry','Physical I','2026-10-08'],['Chemistry','Physical II','2026-10-22'],['Chemistry','Inorganic I','2026-10-30'],['Chemistry','Inorganic II','2026-11-13'],['Chemistry','Organic I','2026-11-29'],['Chemistry','Organic II','2026-12-15']];
const DEFAULT_TEST_CHAPTERS=['Sets','Quadratic Equations','Kinematics','Periodic Table','Structure of Atom'];
const NAV=[['command','Command'],['todo','To-Do'],['deadlines','Deadlines'],['backlog','Backlog'],['tests','Test Hub'],['time','Time Core'],['progress','Progress'],['courses','Courses'],['stats','Stats'],['daily','Daily Report'],['monthly','Monthly Stats'],['review','Daily Review'],['settings','Settings']];
const fresh=()=>({xp:0,tasks:[],tests:[],units:{},deadlines:UNIT_DEADLINES.map(([subject,name,date])=>({id:uid(),subject,name,date})),backlog:[],penalties:{},courses:[],sessions:[],activity:[],cfg:{hours:6,penalty:50,dailyTargetXP:100,monthlyTargetXP:2500},ready:{concepts:false,practice:false,unfamiliar:false,timed:false,doubts:false,revision:false},review:'',dayClosed:false,timer:{mode:'stopped',started:0,elapsed:0},lastDate:today()});
let s=load();
function load(){try{let raw=JSON.parse(localStorage.getItem(KEY)||'null')||{};let out=Object.assign(fresh(),raw);if(!Array.isArray(out.deadlines)||!out.deadlines.length)out.deadlines=UNIT_DEADLINES.map(([subject,name,date])=>({id:uid(),subject,name,date}));if(!Array.isArray(out.activity))out.activity=[];if(!Array.isArray(out.backlog))out.backlog=[];if(!out.cfg)out.cfg={hours:6,penalty:50,dailyTargetXP:100,monthlyTargetXP:2500};if(out.cfg.dailyTargetXP==null)out.cfg.dailyTargetXP=100;if(out.cfg.monthlyTargetXP==null)out.cfg.monthlyTargetXP=2500;delete out.weak;delete out.revision;delete out.questions;return out}catch(e){return fresh()}}
function save(){localStorage.setItem(KEY,JSON.stringify(s));render()}
function today(){let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function uid(){return Date.now()+Math.random().toString(16).slice(2)}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function daysUntil(d){return Math.ceil((new Date(d+'T23:59:59')-new Date())/86400000)}
function late(d){return daysUntil(d)<0}
function fmtMin(m){m=Math.max(0,Math.round(m));return `${Math.floor(m/60)}h ${m%60}m`}
function toast(x){const e=document.getElementById('toast');e.textContent=x;e.style.display='block';setTimeout(()=>e.style.display='none',1600)}
function penaltyCheck(){s.deadlines.forEach(x=>{let u=x.name,d=x.date;if(!s.units[u]&&late(d)&&!s.penalties['unit:'+x.id]){s.backlog.push({id:uid(),name:'Missed deadline: '+u,desc:'Automatic backlog from unit deadline',xp:0,mins:30,due:d,source:'deadline'});s.xp=Math.max(0,s.xp-s.cfg.penalty);s.penalties['unit:'+x.id]=1}});s.tests.forEach(t=>{if(t.status!=='complete'&&t.date&&late(t.date)&&!s.penalties['test:'+t.id]){s.backlog.push({id:uid(),name:'Missed test deadline: '+t.name,desc:'Automatic backlog from test deadline',xp:0,mins:30,due:t.date,source:'deadline'});s.xp=Math.max(0,s.xp-s.cfg.penalty);s.penalties['test:'+t.id]=1}});localStorage.setItem(KEY,JSON.stringify(s))}
function nav(){document.getElementById('nav').innerHTML=NAV.map(([id,n])=>`<button onclick="show('${id}')">${n}</button>`).join('')}
function show(id){document.querySelectorAll('.page').forEach(e=>e.classList.remove('active'));document.getElementById('p-'+id)?.classList.add('active');location.hash=id}
function page(id,title,body){return `<section class="page" id="p-${id}"><h2>${title}</h2>${body}</section>`}
function activeTasks(){return s.tasks.filter(t=>!t.done)}
function estimateRemaining(){return activeTasks().reduce((a,t)=>a+(+t.mins||30),0)+s.tests.filter(t=>t.status!=='complete').reduce((a,t)=>a+t.chapters.filter(c=>!c.done).reduce((b,c)=>b+(+c.mins||30),0),0)}
function readiness(){return Object.values(s.ready).filter(Boolean).length}
function priorityScoreTask(t){let score=0,now=new Date();if(t.due){let d=daysUntil(t.due);score+=d<0?100:d<=1?70:d<=3?45:d<=7?25:8}score+=Math.min(30,(+t.mins||30)/10);score+=t.priority==='High'?25:t.priority==='Medium'?12:0;return score}
function priorities(){let arr=activeTasks().map(t=>({type:'task',id:t.id,name:t.name,mins:+t.mins||30,score:priorityScoreTask(t),why:'task'}));s.deadlines.forEach(x=>{if(!s.units[x.name])arr.push({type:'unit',id:x.id,name:x.name,mins:60,score:(late(x.date)?120:Math.max(10,90-daysUntil(x.date)*4)),why:'unit deadline'});});s.tests.filter(t=>t.status!=='complete').forEach(t=>{let rem=t.chapters.filter(c=>!c.done).reduce((a,c)=>a+(+c.mins||30),0);let d=daysUntil(t.date);arr.push({type:'test',id:t.id,name:'Test: '+t.name,mins:Math.max(30,rem),score:(late(t.date)?140:100-Math.max(0,d)*4)+(t.priority==='High'?30:0),why:'test deadline'});});return arr.sort((a,b)=>b.score-a.score)}
function reality(){let cap=s.cfg.hours*60,rem=estimateRemaining(),target=Math.round(cap*.82),planned=Math.min(target,rem),ratio=rem/Math.max(1,cap);let status=ratio>1.15?'OVERLOADED':ratio>.9?'AGGRESSIVE':'REALISTIC';return {cap,rem,target,planned,status}}
function command(){let r=reality(),p=priorities().slice(0,5);return `<div class="card"><h3>Reality Check</h3><div class="row"><div class="field"><label>Hours I can genuinely give today<input id="hours" type="number" min="0.5" step="0.5" value="${s.cfg.hours}"></label></div><button onclick="setHours()">Recalculate</button></div><p><b class="${r.status==='REALISTIC'?'good':r.status==='AGGRESSIVE'?'warn':'danger'}">${r.status}</b> · ${fmtMin(r.rem)} estimated active work · ${fmtMin(r.planned)} recommended today.</p><div class="bar"><div class="fill" style="width:${Math.min(100,r.planned/Math.max(1,r.cap)*100)}%"></div></div><p class="muted">The engine keeps ~18% of your entered capacity as buffer instead of filling every minute.</p></div><div class="card"><h3>What Should I Do Now?</h3>${p.length?p.map((x,i)=>`<div class="item"><span class="badge">#${i+1}</span> <span class="priority">${esc(x.name)}</span> · ${fmtMin(x.mins)} <span class="muted">· ${x.why}</span>${x.type==='task'?` <button class="right" onclick="completeTask('${x.id}')">Complete</button>`:''}</div>`).join(''):'<p>No active work. Add tasks or tests.</p>'}</div><div class="grid"><div class="card"><h3>Today's Capacity</h3><div class="big">${s.cfg.hours}h</div><p class="muted">Recommended: ${fmtMin(r.planned)}</p></div><div class="card"><h3>XP</h3><div class="big">${s.xp}</div><p class="muted">Productive timer minutes also earn XP.</p></div><div class="card"><h3>Test Readiness</h3><div class="big">${readiness()}/6</div></div></div>`}
function taskForm(t){return `<div class="grid"><label>Name<input id="n-${t.id}" value="${esc(t.name)}"></label><label>Description<input id="d-${t.id}" value="${esc(t.desc)}"></label><label>Minutes<input id="m-${t.id}" type="number" value="${t.mins||30}"></label><label>XP<input id="x-${t.id}" type="number" value="${t.xp||10}"></label><label>Priority<select id="p-${t.id}">${['Low','Medium','High'].map(x=>`<option ${t.priority===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Due date<input id="u-${t.id}" type="date" value="${t.due||''}"></label><label>Unit<input id="unit-${t.id}" value="${esc(t.unit||'')}"></label></div><button onclick="editTask('${t.id}')">Save</button>`}
function todo(){let all=s.tasks;return `<div class="card"><h3>Add Task</h3><div class="grid"><label>Name<input id="newName" placeholder="e.g. Mechanics COM practice"></label><label>Description<input id="newDesc"></label><label>Minutes<input id="newMins" type="number" value="45"></label><label>XP<input id="newXp" type="number" value="10"></label><label>Priority<select id="newPriority"><option>Medium</option><option>High</option><option>Low</option></select></label><label>Due date<input id="newDue" type="date"></label><label>Unit<input id="newUnit"></label></div><button onclick="addTask()">Add Task</button></div>${all.map(t=>`<div class="item ${t.done?'done':''} ${t.source==='deadline'?'overdue':''}"><span class="badge">${t.source==='deadline'?'BACKLOG':'TASK'}</span> <b>${esc(t.name)}</b> · ${t.mins||30}m · ${t.xp||0} XP${t.source==='deadline'?`<p class="danger">Automatic missed-deadline backlog.</p>`:`<details><summary>Edit</summary>${taskForm(t)}</details><p><button onclick="toggleTask('${t.id}')">${t.done?'Undo':'Complete'}</button> <button onclick="moveTask('${t.id}',-1)">↑</button> <button onclick="moveTask('${t.id}',1)">↓</button> <button onclick="deleteTask('${t.id}')">Delete</button></p>`}</div>`).join('')||'<p>No tasks.</p>'}`}
function addTask(){if(!newName.value.trim())return;s.tasks.push({id:uid(),name:newName.value,desc:newDesc.value,mins:+newMins.value||30,xp:+newXp.value||0,priority:newPriority.value,due:newDue.value,unit:newUnit.value,done:false,created:Date.now()});save()}
function editTask(id){let t=s.tasks.find(x=>x.id===id);if(!t)return;t.name=document.getElementById('n-'+id).value;t.desc=document.getElementById('d-'+id).value;t.mins=+document.getElementById('m-'+id).value||30;t.xp=+document.getElementById('x-'+id).value||0;t.priority=document.getElementById('p-'+id).value;t.due=document.getElementById('u-'+id).value;t.unit=document.getElementById('unit-'+id).value;save();toast('Task updated')}
function toggleTask(id){let t=s.tasks.find(x=>x.id===id);if(!t)return;t.done=!t.done;let delta=t.done?(+t.xp||0):-(+t.xp||0);s.xp=Math.max(0,s.xp+delta);s.activity.push({id:uid(),date:today(),at:Date.now(),type:t.done?'task_complete':'task_undo',name:t.name,xp:delta,mins:t.done?(+t.mins||0):0});save()}
function completeTask(id){toggleTask(id)}
function deleteTask(id){s.tasks=s.tasks.filter(x=>x.id!==id);save()}
function moveTask(id,d){let i=s.tasks.findIndex(x=>x.id===id),j=i+d;if(i<0||j<0||j>=s.tasks.length)return;[s.tasks[i],s.tasks[j]]=[s.tasks[j],s.tasks[i]];save()}
function deadlines(){let units=s.deadlines.map(x=>({kind:'Unit',subject:x.subject||'',name:x.name,date:x.date,done:!!s.units[x.name],id:x.id}));let tests=s.tests.map(t=>({kind:'Test',subject:t.subject||'',name:t.name,date:t.date,done:t.status==='complete',id:t.id}));let all=[...units,...tests].sort((a,b)=>a.date.localeCompare(b.date));let active=all.filter(x=>!x.done);return `<div class="card"><h3>Deadline Radar</h3><p class="muted">You can edit a deadline anytime. Completed items leave the active queue; missed active deadlines enter backlog automatically.</p><p><button onclick="addDeadline()">+ Add Deadline</button></p>${active.length?active.map(x=>`<div class="item ${late(x.date)?'overdue':''}"><span class="badge">${x.kind}</span> <b>${esc(x.name)}</b> · ${x.date} · ${late(x.date)?'<span class="danger">MISSED</span>':daysUntil(x.date)+' days left'} <span class="right"><button onclick="editDeadline('${x.id}','${x.kind}')">Edit</button>${x.kind==='Unit'?` <button onclick="toggleUnitById('${x.id}')">Mark complete</button>`:''}</span></div>`).join(''):'<p class="good">No active deadlines.</p>'}</div><div class="card"><h3>Completed / Archived</h3>${all.filter(x=>x.done).map(x=>`<div class="item done"><span class="badge">${x.kind}</span> ${esc(x.name)} · ${x.date} <button class="right" onclick="editDeadline('${x.id}','${x.kind}')">Edit</button>${x.kind==='Unit'?` <button onclick="toggleUnitById('${x.id}')">Undo</button>`:''}</div>`).join('')||'<p>Nothing completed yet.</p>'}</div><div class="card"><h3>Unit Deadline List</h3>${s.deadlines.map(x=>`<div class="item"><b>${esc(x.subject)}</b> · ${esc(x.name)} · ${x.date}<button class="right" onclick="editDeadline('${x.id}','Unit')">Edit</button> <button onclick="deleteDeadline('${x.id}')">Delete</button></div>`).join('')}</div>`}
function addDeadline(){let subject=prompt('Subject (Maths / Physics / Chemistry):','Maths');if(subject===null)return;let name=prompt('Deadline / unit name:','New Unit');if(!name)return;let date=prompt('Deadline date (YYYY-MM-DD):',today());if(!date)return;s.deadlines.push({id:uid(),subject,name,date});save();toast('Deadline added')}
function editDeadline(id,kind){if(kind==='Unit'){let d=s.deadlines.find(x=>x.id===id);if(!d)return;let subject=prompt('Subject:',d.subject||'');if(subject===null)return;let name=prompt('Deadline / unit name:',d.name);if(!name)return;let date=prompt('Deadline date (YYYY-MM-DD):',d.date);if(!date)return;let old=d.name;d.subject=subject;d.name=name;d.date=date;if(old!==name&&s.units[old]){s.units[name]=s.units[old];delete s.units[old]}save();toast('Deadline updated')}else{let t=s.tests.find(x=>x.id===id);if(!t)return;let date=prompt('Test deadline (YYYY-MM-DD):',t.date||today());if(date===null)return;t.date=date;save();toast('Test deadline updated')}}
function deleteDeadline(id){if(!confirm('Delete this unit deadline?'))return;s.deadlines=s.deadlines.filter(x=>x.id!==id);save();toast('Deadline deleted')}
function toggleUnitById(id){let d=s.deadlines.find(x=>x.id===id);if(d)toggleUnit(d.name)}

function courses(){return `<div class="card"><h3>Course Library</h3><p class="muted">Store the exact courses you are using and track completion.</p><div class="grid"><label>Course name<input id="courseName" placeholder="e.g. Calculus Complete Course"></label><label>YouTube URL<input id="courseUrl" placeholder="https://youtube.com/..."></label><label>Progress %<input id="courseProgress" type="number" min="0" max="100" value="0"></label></div><button onclick="addCourse()">Add Course</button></div>${s.courses.map(c=>`<div class="item"><b>${esc(c.name)}</b><p class="muted">${esc(c.url||'')} · ${c.progress||0}%</p><div class="bar"><div class="fill" style="width:${Math.min(100,Math.max(0,+c.progress||0))}%"></div></div><p><button onclick="editCourse('${c.id}')">Edit</button> <button onclick="deleteCourse('${c.id}')">Delete</button></p></div>`).join('')||'<p>No courses added.</p>'}`}
function addCourse(){if(!courseName.value.trim())return;s.courses.push({id:uid(),name:courseName.value,url:courseUrl.value,progress:Math.max(0,Math.min(100,+courseProgress.value||0))});save();toast('Course added')}
function editCourse(id){let c=s.courses.find(x=>x.id===id);if(!c)return;let n=prompt('Course name:',c.name);if(n===null)return;let u=prompt('YouTube URL:',c.url||'');if(u===null)return;let pr=prompt('Progress %:',c.progress||0);if(pr===null)return;c.name=n.trim()||c.name;c.url=u.trim();c.progress=Math.max(0,Math.min(100,+pr||0));save()}
function deleteCourse(id){if(confirm('Delete this course?')){s.courses=s.courses.filter(x=>x.id!==id);save()}}
function progress(){return `<div class="grid">${s.deadlines.map(x=>`<div class="item ${late(x.date)&&!s.units[x.name]?'overdue':''}"><span class="badge">${esc(x.subject)}</span><b>${esc(x.name)}</b><p class="muted">Deadline: ${x.date}</p><button onclick="toggleUnitById('${x.id}')">${s.units[x.name]?'Undo completion':'Mark complete'}</button> <button onclick="editDeadline('${x.id}','Unit')">Edit deadline</button></div>`).join('')}</div>`}

function toggleUnit(u){s.units[u]=!s.units[u];save()}
function toggleUnitById(id){let d=s.deadlines.find(x=>x.id===id);if(d)toggleUnit(d.name)}
function addDeadline(){let subject=prompt('Subject (Maths / Physics / Chemistry):','Maths');if(subject===null)return;let name=prompt('Deadline / unit name:','New Unit');if(!name)return;let date=prompt('Deadline date (YYYY-MM-DD):',today());if(!date)return;s.deadlines.push({id:uid(),subject,name,date});save();toast('Deadline added')}
function deleteDeadline(id){if(!confirm('Delete this unit deadline?'))return;s.deadlines=s.deadlines.filter(x=>x.id!==id);save();toast('Deadline deleted')}
function backlog(){let items=s.backlog;return `<div class="card"><h3>Missed-Deadline Backlog</h3><p class="muted">Automatic items created when a unit or test deadline is missed. Resolve them here instead of letting them disappear.</p><p><b>${items.filter(x=>!x.done).length}</b> active · <b>${items.filter(x=>x.done).length}</b> resolved</p></div>${items.map(x=>`<div class="item ${x.done?'done':''}"><span class="badge">MISSED DEADLINE</span> <b>${esc(x.name)}</b><p>${esc(x.desc||'')} · Original deadline: ${esc(x.due||'')}</p><button onclick="toggleBacklog('${x.id}')">${x.done?'Reopen':'Resolve'}</button> <button onclick="backlogToTask('${x.id}')">Make To-Do</button> <button onclick="deleteBacklog('${x.id}')">Delete</button></div>`).join('')||'<p>No missed deadlines. Good.</p>'}`}
function toggleBacklog(id){let x=s.backlog.find(b=>b.id===id);if(!x)return;x.done=!x.done;save()}
function backlogToTask(id){let x=s.backlog.find(b=>b.id===id);if(!x)return;s.tasks.push({id:uid(),name:x.name.replace(/^Missed deadline: /,''),desc:x.desc||'Recovered from missed deadline',mins:x.mins||30,xp:10,priority:'High',due:'',unit:'Backlog',done:false,created:Date.now()});x.done=true;save();toast('Added to To-Do')}
function deleteBacklog(id){s.backlog=s.backlog.filter(x=>x.id!==id);save()}

function testEditor(t){return `<div class="grid"><label>Name<input id="tn-${t.id}" value="${esc(t.name)}"></label><label>Date<input id="td-${t.id}" type="date" value="${t.date}"></label><label>Subjects<input id="ts-${t.id}" value="${esc(t.subject||'')}" ></label><label>Priority<select id="tp-${t.id}">${['Low','Medium','High'].map(x=>`<option ${t.priority===x?'selected':''}>${x}</option>`).join('')}</select></label></div><button onclick="editTest('${t.id}')">Save Test Details</button><h4>Editable syllabus</h4>${t.chapters.map(c=>`<div class="item ${c.done?'done':''}"><input id="cn-${c.id}" value="${esc(c.name)}"><input id="cm-${c.id}" type="number" value="${c.mins||30}" style="max-width:120px"><button onclick="editChapter('${t.id}','${c.id}')">Save</button><button onclick="toggleChapter('${t.id}','${c.id}')">${c.done?'Undo':'Done'}</button><button onclick="deleteChapter('${t.id}','${c.id}')">Delete</button></div>`).join('')}<div class="row"><input id="newch-${t.id}" placeholder="New chapter"><input id="newcm-${t.id}" type="number" value="30" style="max-width:120px"><button onclick="addChapter('${t.id}')">Add Chapter</button></div>`}
function tests(){let vals=Object.keys(s.ready),n=readiness();return `<div class="card"><h3>Test Readiness ${n}/6</h3><div class="grid">${vals.map(k=>`<button onclick="s.ready['${k}']=!s.ready['${k}'];save()">${s.ready[k]?'✓ ':''}${k.replace(/([A-Z])/g,' $1')}</button>`).join('')}</div><div class="bar"><div class="fill" style="width:${n/6*100}%"></div></div></div><div class="card"><h3>Add Test Deadline</h3><div class="grid"><label>Name<input id="testName"></label><label>Date<input id="testDate" type="date"></label><label>Subjects<input id="testSubject"></label><label>Priority<select id="testPriority"><option>High</option><option>Medium</option><option>Low</option></select></label></div><button onclick="addTest()">Add Test</button></div>${s.tests.map(t=>`<div class="card ${late(t.date)&&t.status!=='complete'?'overdue':''}"><h3>${esc(t.name)} <span class="badge">${t.status==='complete'?'COMPLETE':t.date}</span></h3><p>${esc(t.subject||'')} · ${t.priority} priority · ${t.chapters.filter(c=>c.done).length}/${t.chapters.length} chapters ready</p><details><summary>Edit Test + Syllabus</summary>${testEditor(t)}</details><p><button onclick="quickPrep('${t.id}')">Create Prep Tasks</button> <button onclick="toggleTest('${t.id}')">${t.status==='complete'?'Reopen':'Complete Test'}</button> <button onclick="deleteTest('${t.id}')">Delete</button></p></div>`).join('')}`}
function addTest(){if(!testName.value||!testDate.value)return;let chapters=DEFAULT_TEST_CHAPTERS.map(n=>({id:uid(),name:n,mins:30,done:false}));s.tests.push({id:uid(),name:testName.value,date:testDate.value,subject:testSubject.value,priority:testPriority.value,status:'open',chapters});save()}
function editTest(id){let t=s.tests.find(x=>x.id===id);t.name=document.getElementById('tn-'+id).value;t.date=document.getElementById('td-'+id).value;t.subject=document.getElementById('ts-'+id).value;t.priority=document.getElementById('tp-'+id).value;save()}
function addChapter(tid){let t=s.tests.find(x=>x.id===tid);let n=document.getElementById('newch-'+tid).value;if(!n)return;t.chapters.push({id:uid(),name:n,mins:+document.getElementById('newcm-'+tid).value||30,done:false});save()}
function editChapter(tid,cid){let t=s.tests.find(x=>x.id===tid),c=t.chapters.find(x=>x.id===cid);c.name=document.getElementById('cn-'+cid).value;c.mins=+document.getElementById('cm-'+cid).value||30;save()}
function toggleChapter(tid,cid){let t=s.tests.find(x=>x.id===tid),c=t.chapters.find(x=>x.id===cid);c.done=!c.done;save()}
function deleteChapter(tid,cid){let t=s.tests.find(x=>x.id===tid);t.chapters=t.chapters.filter(c=>c.id!==cid);save()}
function toggleTest(id){let t=s.tests.find(x=>x.id===id);t.status=t.status==='complete'?'open':'complete';s.activity.push({id:uid(),date:today(),at:Date.now(),type:t.status==='complete'?'test_complete':'test_reopen',name:t.name,xp:0,mins:0});save()}
function deleteTest(id){s.tests=s.tests.filter(x=>x.id!==id);save()}
function quickPrep(id){let t=s.tests.find(x=>x.id===id);t.chapters.filter(c=>!c.done).forEach(c=>{if(!s.tasks.some(x=>x.testId===id&&x.chapterId===c.id&&!x.done))s.tasks.push({id:uid(),name:'Prep: '+c.name,desc:'Test: '+t.name,mins:c.mins||30,xp:10,priority:t.priority,due:t.date,unit:'Test Prep',done:false,testId:id,chapterId:c.id})});save();toast('Prep tasks created')}
function timeCore(){let elapsed=s.timer.elapsed;if(s.timer.mode!=='stopped'&&s.timer.started)elapsed+=(Date.now()-s.timer.started)/60000;let total=s.sessions.reduce((a,x)=>a+x.mins,0);return `<div class="card"><h3>Time Core</h3><div class="timer">${fmtClock(elapsed)}</div><p style="text-align:center"><span class="pill">Mode: ${s.timer.mode}</span></p><div class="row" style="justify-content:center"><button onclick="startTimer('productive')">Productive</button><button onclick="startTimer('break')">Break</button><button onclick="startTimer('lost')">Lost</button><button onclick="pauseTimer()">Pause</button><button onclick="resetTimer()">Reset</button></div><p class="muted">Productive time earns 1 XP per 5 minutes when a session is saved.</p></div><div class="card"><h3>Session History</h3>${s.sessions.slice().reverse().map(x=>`<div class="item"><span class="badge">${x.mode}</span> ${fmtMin(x.mins)} · ${new Date(x.at).toLocaleString()}</div>`).join('')||'<p>No sessions yet.</p>'}<p><b>${fmtMin(total)}</b> total recorded</p></div>`}
function fmtClock(min){let sec=Math.floor(min*60),h=Math.floor(sec/3600);sec%=3600;let m=Math.floor(sec/60),s2=sec%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s2).padStart(2,'0')}`}
let timerTick=null;function startTimer(mode){if(s.timer.mode!=='stopped')saveTimer();s.timer.mode=mode;s.timer.started=Date.now();s.timer.elapsed=0;if(timerTick)clearInterval(timerTick);timerTick=setInterval(()=>{if(location.hash==='#time')document.getElementById('p-time').innerHTML=page('time','Time Core',timeCore()).replace(/^<section[^>]*>|<\/section>$/g,'')},1000);render()}
function saveTimer(){if(s.timer.mode==='stopped')return;let mins=s.timer.elapsed+(Date.now()-s.timer.started)/60000;if(mins>=.05){s.sessions.push({mode:s.timer.mode,mins,at:Date.now()});if(s.timer.mode==='productive'){let gained=Math.floor(mins/5);s.xp+=gained;s.activity.push({id:uid(),date:today(),at:Date.now(),type:'productive_time',name:'Productive timer',xp:gained,mins})}}s.timer={mode:'stopped',started:0,elapsed:0};localStorage.setItem(KEY,JSON.stringify(s))}
function pauseTimer(){saveTimer();render()}
function resetTimer(){s.timer={mode:'stopped',started:0,elapsed:0};save()}
function dateKey(d){return d instanceof Date?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`:String(d).slice(0,10)}
function monthKey(d){let x=d instanceof Date?d:new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`}
function monthLabel(key){let [y,m]=key.split('-');return new Date(+y,+m-1,1).toLocaleDateString(undefined,{month:'short',year:'numeric'})}
function dayActivity(day){return s.activity.filter(a=>a.date===day)}
function dayStats(day){let acts=dayActivity(day),sessions=s.sessions.filter(x=>dateKey(new Date(x.at))===day);let productive=sessions.filter(x=>x.mode==='productive').reduce((a,x)=>a+x.mins,0);let tasks=acts.filter(a=>a.type==='task_complete').length;let xp=acts.reduce((a,x)=>a+(+x.xp||0),0);return {xp,tasks,productive,minutes:productive}}
function monthStats(key){let acts=s.activity.filter(a=>monthKey(a.date||a.at)===key),sessions=s.sessions.filter(x=>monthKey(new Date(x.at))===key);return {xp:acts.reduce((a,x)=>a+(+x.xp||0),0),tasks:acts.filter(a=>a.type==='task_complete').length,productive:sessions.filter(x=>x.mode==='productive').reduce((a,x)=>a+x.mins,0),tests:acts.filter(a=>a.type==='test_complete').length,missed:s.backlog.filter(x=>monthKey(x.due||x.created||Date.now())===key).length}}
function targetCard(){return `<div class="card"><h3>XP Targets</h3><div class="grid"><label>Daily target XP<input id="dailyTarget" type="number" min="0" value="${s.cfg.dailyTargetXP}"></label><label>Monthly target XP<input id="monthlyTarget" type="number" min="0" value="${s.cfg.monthlyTargetXP}"></label></div><button onclick="saveTargets()">Save XP Targets</button></div>`}
function saveTargets(){s.cfg.dailyTargetXP=Math.max(0,+dailyTarget.value||0);s.cfg.monthlyTargetXP=Math.max(0,+monthlyTarget.value||0);save();toast('XP targets updated')}
function stats(){let ds=dayStats(today()),mk=monthKey(today()),ms=monthStats(mk),dailyPct=s.cfg.dailyTargetXP?Math.min(100,ds.xp/s.cfg.dailyTargetXP*100):0,monthlyPct=s.cfg.monthlyTargetXP?Math.min(100,ms.xp/s.cfg.monthlyTargetXP*100):0;return `${targetCard()}<div class="grid"><div class="card"><div class="big">${s.xp}</div><p>Total XP</p></div><div class="card"><div class="big">${ds.xp}</div><p>Today XP</p></div><div class="card"><div class="big">${fmtMin(ds.productive)}</div><p>Today productive time</p></div><div class="card"><div class="big">${ds.tasks}</div><p>Today tasks</p></div></div><div class="card"><h3>Today vs target</h3><div class="bar"><div class="fill" style="width:${dailyPct}%"></div></div><p>${ds.xp} / ${s.cfg.dailyTargetXP} XP · ${Math.round(dailyPct)}%</p></div><div class="card"><h3>This month vs target</h3><div class="bar"><div class="fill" style="width:${monthlyPct}%"></div></div><p>${ms.xp} / ${s.cfg.monthlyTargetXP} XP · ${Math.round(monthlyPct)}%</p></div>`}
function daily(){let ds=dayStats(today()),pct=s.cfg.dailyTargetXP?Math.min(100,ds.xp/s.cfg.dailyTargetXP*100):0,acts=dayActivity(today()).slice().reverse();return `<div class="card"><h3>Daily Report · ${today()}</h3><div class="grid"><div><div class="big">${fmtMin(ds.productive)}</div><p>productive hours</p></div><div><div class="big">${ds.tasks}</div><p>tasks completed</p></div><div><div class="big">${ds.xp}</div><p>XP earned</p></div></div><div class="bar"><div class="fill" style="width:${pct}%"></div></div><p><b>${Math.round(pct)}%</b> of daily XP target · ${ds.xp}/${s.cfg.dailyTargetXP} XP</p></div><div class="card"><h3>Today's activity</h3>${acts.map(a=>`<div class="item"><span class="badge">${esc(a.type)}</span> ${esc(a.name||'Activity')} · ${a.xp>=0?'+':''}${a.xp||0} XP${a.mins?` · ${fmtMin(a.mins)}`:''}</div>`).join('')||'<p class="muted">No tracked activity yet. Use Time Core and complete tasks to build the report.</p>'}</div>`}
function graph(title,rows,valueKey,target){let max=Math.max(1,...rows.map(r=>r[valueKey]),target||0);return `<div class="card"><h3>${title}</h3><div class="graph">${rows.map(r=>`<div class="gcol"><div class="gvalue">${valueKey==='productive'?fmtMin(r[valueKey]):r[valueKey]}</div><div class="gbar"><div class="gfill" style="height:${Math.max(3,r[valueKey]/max*100)}%"></div></div><div class="glabel">${esc(r.label)}</div></div>`).join('')}</div></div>`}
function monthly(){let now=new Date(),keys=[];for(let i=5;i>=0;i--){let d=new Date(now.getFullYear(),now.getMonth()-i,1);keys.push(monthKey(d))}let rows=keys.map(k=>({key:k,label:monthLabel(k),...monthStats(k)}));return `<div class="card"><h3>Monthly Stats</h3><p class="muted">Track the things that actually matter: productive hours, completed tasks and XP earned. Targets are shown alongside your progress.</p><div class="grid"><div><div class="big">${rows[rows.length-1].xp}</div><p>Current month XP / ${s.cfg.monthlyTargetXP} target</p></div><div><div class="big">${fmtMin(rows[rows.length-1].productive)}</div><p>Current month productive time</p></div><div><div class="big">${rows[rows.length-1].tasks}</div><p>Current month tasks</p></div></div></div>${graph('XP earned by month',rows,'xp',s.cfg.monthlyTargetXP)}${graph('Productive time by month',rows,'productive',0)}${graph('Tasks completed by month',rows,'tasks',0)}<div class="tablewrap"><table class="table"><tr><th>Month</th><th>XP</th><th>Target</th><th>Productive</th><th>Tasks</th><th>Tests</th><th>Missed</th></tr>${rows.map(r=>`<tr><td>${esc(r.label)}</td><td>${r.xp}</td><td>${s.cfg.monthlyTargetXP}</td><td>${fmtMin(r.productive)}</td><td>${r.tasks}</td><td>${r.tests}</td><td>${r.missed}</td></tr>`).join('')}</table></div>`}
function review(){return `<div class="card"><textarea id="reviewText" placeholder="Biggest win · biggest leak · carry forward">${esc(s.review)}</textarea><button onclick="saveReview()">Save Review</button> <button onclick="closeDay()">Close Day</button><p>${s.dayClosed?'Day closed.':'Day open.'}</p></div>`}
function saveReview(){s.review=reviewText.value;save()}function closeDay(){s.review=reviewText.value;s.dayClosed=true;save()}
function settings(){return `<div class="card"><h3>Settings</h3><div class="grid"><label>Default daily capacity (hours)<input id="setHours" type="number" step="0.5" value="${s.cfg.hours}"></label><label>Missed deadline XP penalty<input id="setPenalty" type="number" value="${s.cfg.penalty}"></label></div><button onclick="saveSettings()">Save</button></div><div class="card"><h3>Data</h3><button onclick="exportData()">Export JSON</button><button onclick="resetData()">Reset All</button><p class="muted">Keep exported JSON private. GitHub should contain code, not your tracker data.</p></div>`}
function saveSettings(){s.cfg.hours=+setHours.value||6;s.cfg.penalty=+setPenalty.value||50;save()}
function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(s,null,2)],{type:'application/json'}));a.download='jee-ascension-v5-backup.json';a.click()}
function resetData(){if(confirm('Reset all V5 tracker data?')){localStorage.removeItem(KEY);location.reload()}}
function setHours(){s.cfg.hours=+hours.value||1;save();toast('Reality Check recalculated')}
function render(){penaltyCheck();nav();document.getElementById('app').innerHTML=page('command','Command Center',command())+page('todo','Editable To-Do',todo())+page('deadlines','Deadline Radar',deadlines())+page('backlog','Missed-Deadline Backlog',backlog())+page('tests','Test Hub',tests())+page('time','Time Core',timeCore())+page('progress','Progress Board',progress())+page('courses','Course Library',courses())+page('stats','Ascension Stats',stats())+page('daily','Daily Report',daily())+page('monthly','Monthly Stats',monthly())+page('review','Daily Review',review())+page('settings','Settings',settings());show(location.hash.slice(1)||'command')}
render();
